on:
  pull_request:
    paths:
      - 'demo-app/**'

defaults:
  run:
    shell: bash
    working-directory: demo-app

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: PR Build for demo-app
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: PR Landmine
        uses: tylermurry/github-pr-landmine@v1
        with:
          token: ${{ github.token }}
          test-command: 'npm test' # <-- Use your test command here
